# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_camiseta_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcetine',
            name='img',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
